[[collection]]
type = "box"
title = "Veno's Blog"
rotate = false
link =  "https://v3n0.top/"
img = "https://raw.githubusercontent.com/U1traVeno/U1traVeno.github.io/refs/heads/main/assets/avatar-veno.jpg"
subtitle = "Veno 的个人博客"
