layout = "tile"

[[item]]
title = "Macesuted's Blog"
rotate = true
link =  "https://macesuted.moe/"
image = "https://avatars.githubusercontent.com/u/57275149"
subtitle = "我缓慢吐出一串啊吧啊吧并不再想说话"

[[item]]
title = "Veno's Blog"
rotate = true
link =  "https://v3n0.top/"
image = "https://raw.githubusercontent.com/U1traVeno/U1traVeno.github.io/refs/heads/main/assets/avatar-veno.jpg"
subtitle = "Veno 的个人博客"

[[item]]
title = "CAICAIIs' world"
rotate = true
link = "https://caicaiis.cc/"
image = "https://caicaiis.cc/assets/images/photo.jpg"
subtitle = "愚者在月影之中怀抱虚妄"

[[item]]
title = "Woman's World"
rotate = true
link =  "https://zhoudapig13.github.io/my-blog/#home"
image = "https://zhoudapig13.github.io/my-blog/resources/uploads/avatar.png"
subtitle = "周大妈的知识厨房"
